name: CI/CD
#  runs every time code is pushed to main repository 
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
# checkouts the code on github runner
      - name: Checkout Code
        uses: actions/checkout@v4
# installs java on runner 
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with: 
          name: springboot-jar
          path: target/*.jar
          retention-day: 7
      - name : upload test reports background
        uses: actions/upload-artifact@v4
        with: 
          name: test-reports 
          path: target/surefire-reports
      
      # sonar check
      - name: verfiy sonar token
        run: |
          if [ -z "$SONAR_QUBE_TOKEN" ]; then
            echo "SONAR_QUBE_TOKEN is not set. please set the token in the repository secrets."
            exit 1
          else
            echo "SONAR_QUBE_TOKEN is set."
            fi
        env:
          SONAR_QUBE_TOKEN: ${{ secrets.SONAR_QUBE_SECRET }}    

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_QUBE_SECRET }}
        with:
          args: >
            -Dsonar.projectKey=viraj6108
            -Dsonar.organization=Viraj6108

        # Configure AWS credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build docker image
        run: |
          docker build -t demo-app .
          docker tag demo-app:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha}}

      - name: push docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha}}


      # deployment 
  deploy:
      needs: build
      runs-on: ubuntu-latest

      environment:
        name: production

      steps:

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Deploy ECS
          run: |
                aws ecs update-service \
                --cluster ${{ secrets.ECS_CLUSTER }} \
                --service ${{ secrets.ECS_SERVICE }} \
                --force-new-deployment
